# Generated by Django 5.0.3 on 2024-05-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Selfcare', 'Selfcare')], max_length=400, null=True),
        ),
    ]
