# Generated by Django 5.0.3 on 2024-05-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Education & Learning', 'Education & Learning'), ('Self care', 'Self care'), ('Travel', 'Travel'), ('Internet', 'Internet'), ('Airlines', 'Airlines'), ('Insurance', 'Insurance'), ('Fuel', 'Fuel'), ('Groceries', 'Groceries'), ('Hotels', 'Hotels'), ('Electricity', 'Electricity'), ('Internet', 'Internet'), ('Food', 'Food'), ('Others', 'Others')], max_length=400, null=True),
        ),
    ]
