# Generated by Django 5.0.3 on 2024-05-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Side Job', 'Side Job')], max_length=400, null=True),
        ),
    ]
