# Generated by Django 5.0.3 on 2024-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
